### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by 1171257311** [EmbodiedVision/emfusion#1]
Hello! What a nice job! Thank you for your open source.
Today,when I compile the project, I got an error:

`/home/wei/Documents/project/emfusion/src/core/EMFusion.cpp: In member function ‘void emf::EMFusion::writeMeshVis(const boost::filesystem::path&)’:
/home/wei/Documents/project/emfusion/src/core/EMFusion.cpp:1022:34: error: use of ‘mesh_vis’ before deduction of ‘auto’
     for ( const auto& mesh_vis : mesh_vis ) {
                                  ^
src/CMakeFiles/emfusion.dir/build.make:2766: recipe for target 'src/CMakeFiles/emfusion.dir/core/EMFusion.cpp.o' failed
make[2]: *** [src/CMakeFiles/emfusion.dir/core/EMFusion.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:163: recipe for target 'src/CMakeFiles/emfusion.dir/all' failed
make[1]: *** [src/CMakeFiles/emfusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

It seems that, there is a code mistake in  EMFusion.cpp:1022,which is :

`for ( const auto& mesh_vis : mesh_vis ) {
        writeImage ( mesh_vis_out, mesh_vis.first, mesh_vis.second );
    }`

and i change it to : 
`for ( const auto& mesh : mesh_vis ) {
        writeImage ( mesh_vis_out, mesh.first, mesh.second );
    }`
and it succeed.

**Comment by streckus** [comment]
Hi! Thank you for your feedback! I just updated the code with a solution similar to the one you suggested.
